"use client"

import { useState } from "react"
import { RefreshCw, Clock, Send } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { supabase } from "@/lib/supabase"

const topicSuggestions = [
  "How black holes form",
  "Why the sky is blue",
  "How vaccines work",
  "Why we dream",
  "How plants communicate",
  "Why ice floats on water",
]

export function GenerateContent() {
  const [prompt, setPrompt] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [isPosting, setIsPosting] = useState(false)
  const [isScheduling, setIsScheduling] = useState(false)
  const [posted, setPosted] = useState(false)
  const [scheduled, setScheduled] = useState(false)
  const [scheduledTime, setScheduledTime] = useState("")
  const [generatedContent, setGeneratedContent] = useState<{ topic: string; body: string; provider: string } | null>(null)

  async function handleGenerate(topic?: string) {
    const value = topic ?? prompt
    if (!value.trim()) return
    if (topic) setPrompt(topic)
    setIsGenerating(true)
    setPosted(false)
    setScheduled(false)

    const res = await fetch("/api/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ topic: value }),
    })
    const data = await res.json()
    setGeneratedContent({ topic: value, body: data.body, provider: data.provider })
    setIsGenerating(false)
  }

  async function handlePostNow() {
    if (!generatedContent) return
    setIsPosting(true)
    const message = `**${generatedContent.topic}**\n\n${generatedContent.body}\n\n*Generated by ${generatedContent.provider}*`
    await fetch("/api/post-to-discord", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ content: message }),
    })

    // Save to DB as posted
    await supabase.from("posts").insert({
      topic: generatedContent.topic,
      content: generatedContent.body,
      platform: "discord",
      scheduled_time: new Date().toISOString(),
      status: "posted",
    })

    setIsPosting(false)
    setPosted(true)
  }

  async function handleSchedule() {
    if (!generatedContent || !scheduledTime) return
    setIsScheduling(true)

    const { error } = await supabase.from("posts").insert({
      topic: generatedContent.topic,
      content: generatedContent.body,
      platform: "discord",
      scheduled_time: new Date(scheduledTime).toISOString(),
      status: "scheduled",
    })

    setIsScheduling(false)
    if (!error) setScheduled(true)
  }

  return (
    <div className="p-8 max-w-3xl mx-auto">
      <div className="mb-8">
        <h1 className="text-2xl font-semibold text-foreground mb-2">Generate Content</h1>
        <p className="text-muted-foreground">Create engaging educational content and post or schedule it to Discord.</p>
      </div>

      <Card className="mb-6 border-border shadow-sm">
        <CardContent className="pt-6">
          <Textarea
            placeholder="Describe what you want to teach…"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            className="min-h-[140px] text-base resize-none border-border bg-background placeholder:text-muted-foreground focus-visible:ring-primary"
          />

          <div className="mt-4">
            <p className="text-xs text-muted-foreground mb-2">Try a suggestion:</p>
            <div className="flex flex-wrap gap-2">
              {topicSuggestions.map((suggestion) => (
                <button
                  key={suggestion}
                  onClick={() => handleGenerate(suggestion)}
                  className="px-3 py-1.5 text-sm rounded-full bg-secondary text-muted-foreground hover:bg-border hover:text-foreground transition-colors border border-border"
                >
                  {suggestion}
                </button>
              ))}
            </div>
          </div>

          <div className="mt-6">
            <Button
              onClick={() => handleGenerate()}
              disabled={isGenerating || !prompt.trim()}
              className="px-6"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : "Generate"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {generatedContent && (
        <Card className="border-border shadow-sm">
          <CardHeader className="pb-4">
            <div className="flex items-center justify-between">
              <CardTitle className="text-lg font-semibold text-foreground">
                {generatedContent.topic}
              </CardTitle>
              <span className="text-xs text-muted-foreground">
                {generatedContent.body.length} chars · via {generatedContent.provider}
              </span>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {generatedContent.body.split("\n\n").map((paragraph, index) => (
                <p key={index} className="text-foreground leading-relaxed">
                  {paragraph}
                </p>
              ))}
            </div>

            {/* Schedule picker */}
            <div className="mt-6 pt-6 border-t border-border">
              <p className="text-sm font-medium text-foreground mb-3 flex items-center gap-2">
                <Clock className="w-4 h-4" />
                Schedule for later
              </p>
              <div className="flex gap-3 items-center flex-wrap">
                <input
                  type="datetime-local"
                  value={scheduledTime}
                  onChange={(e) => setScheduledTime(e.target.value)}
                  className="px-3 py-2 text-sm rounded-md border border-border bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary"
                />
                <Button
                  onClick={handleSchedule}
                  disabled={isScheduling || !scheduledTime || scheduled}
                  variant="secondary"
                  className="px-4"
                >
                  {scheduled ? "Scheduled ✓" : isScheduling ? "Saving…" : "Schedule"}
                </Button>
              </div>
              {scheduled && (
                <p className="text-xs text-muted-foreground mt-2">
                  Post saved — it will be sent automatically at the scheduled time.
                </p>
              )}
            </div>

            <div className="flex items-center justify-between mt-6 pt-4 border-t border-border">
              <button
                onClick={() => handleGenerate()}
                disabled={isGenerating}
                className="text-sm text-primary hover:text-primary/80 font-medium flex items-center gap-1.5 transition-colors disabled:opacity-50"
              >
                <RefreshCw className={`w-3.5 h-3.5 ${isGenerating ? "animate-spin" : ""}`} />
                Regenerate
              </button>
              <Button
                onClick={handlePostNow}
                disabled={isPosting || posted}
                variant={posted ? "secondary" : "default"}
                className="px-5 flex items-center gap-2"
              >
                <Send className="w-4 h-4" />
                {posted ? "Posted ✓" : isPosting ? "Posting…" : "Post Now"}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
